/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgKulturniAkce;

import KalendarUdalosti.IKalendarUdalosti;
import KalendarUdalosti.IUdalost;
import KalendarUdalosti.KalendarUdalosti;
import KalendarUdalosti.Udalost;
import java.awt.Color;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author George
 */
public class ProgKulturniAkce extends javax.swing.JFrame {

    IKalendarUdalosti kalendarUdalosti;
    IUdalost udalostZpristupnena;
    IUdalost udalosti[];

    /**
     * Creates new form ProgKulturniAkce
     */
    public ProgKulturniAkce() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButUloz = new javax.swing.JButton();
        jButNacti = new javax.swing.JButton();
        jButZrus = new javax.swing.JButton();
        Konec = new javax.swing.JButton();
        jButZaloz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxFUloz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxFNacti = new javax.swing.JTextField();
        jButNastavVelikostPriority = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTxtFNastavVelikostPriority = new javax.swing.JTextField();
        jLblVelikostPriority = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtACelkova = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtANeutridena = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtFNazevMesta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtFNazevAkce = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtFDen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtFMesic = new javax.swing.JTextField();
        jButZpristupni = new javax.swing.JButton();
        jButOdeber = new javax.swing.JButton();
        jButReorganizuj = new javax.swing.JButton();
        jButVloz = new javax.swing.JButton();
        jButGeneruj = new javax.swing.JButton();
        jButVypisUtridene = new javax.swing.JButton();
        jButVypisNeutridene = new javax.swing.JButton();
        jButVypis = new javax.swing.JButton();
        jButVlozAkce = new javax.swing.JButton();
        jButOdeberAkce = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtAUtridena = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SemestralniPraceC");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("HlavniOvladaciTlacitka");

        jButUloz.setText("Uloz");
        jButUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButUlozActionPerformed(evt);
            }
        });

        jButNacti.setText("Nacti");
        jButNacti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNactiActionPerformed(evt);
            }
        });

        jButZrus.setText("Zrus");
        jButZrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButZrusActionPerformed(evt);
            }
        });

        Konec.setText("Konec");
        Konec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonecActionPerformed(evt);
            }
        });

        jButZaloz.setText("Zaloz");
        jButZaloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButZalozActionPerformed(evt);
            }
        });

        jLabel1.setText("Nazev souboru:");

        jLabel2.setText("Nazev souboru:");

        jButNastavVelikostPriority.setText("NastevVelikostPriority");
        jButNastavVelikostPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNastavVelikostPriorityActionPerformed(evt);
            }
        });

        jButton3.setText("VelikostPriority");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTxtFNastavVelikostPriority.setText("0");

        jLblVelikostPriority.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Konec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButZrus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButNacti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButUloz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButZaloz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxFNacti)
                            .addComponent(jTxFUloz)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButNastavVelikostPriority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblVelikostPriority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtFNastavVelikostPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButUloz)
                    .addComponent(jLabel1)
                    .addComponent(jTxFUloz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButNacti)
                    .addComponent(jLabel2)
                    .addComponent(jTxFNacti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButZrus)
                    .addComponent(jButNastavVelikostPriority)
                    .addComponent(jTxtFNastavVelikostPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLblVelikostPriority)
                    .addComponent(jButZaloz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Konec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTxtACelkova.setColumns(20);
        jTxtACelkova.setRows(5);
        jScrollPane1.setViewportView(jTxtACelkova);

        jTxtANeutridena.setColumns(20);
        jTxtANeutridena.setRows(5);
        jScrollPane2.setViewportView(jTxtANeutridena);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nazev mesta:");

        jTxtFNazevMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFNazevMestaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nazev akce:");

        jLabel5.setText("Datum:");

        jLabel6.setText("Den:");

        jTxtFDen.setText("0");

        jLabel7.setText("Mesic:");

        jTxtFMesic.setText("0");

        jButZpristupni.setText("Zpristupni");
        jButZpristupni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButZpristupniActionPerformed(evt);
            }
        });

        jButOdeber.setText("Odeber");
        jButOdeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOdeberActionPerformed(evt);
            }
        });

        jButReorganizuj.setText("Reorganizuj");
        jButReorganizuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButReorganizujActionPerformed(evt);
            }
        });

        jButVloz.setText("Vloz");
        jButVloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVlozActionPerformed(evt);
            }
        });

        jButGeneruj.setText("Generuj");
        jButGeneruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGenerujActionPerformed(evt);
            }
        });

        jButVypisUtridene.setText("VypisUtridene");
        jButVypisUtridene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVypisUtrideneActionPerformed(evt);
            }
        });

        jButVypisNeutridene.setText("VypisNeutridene");
        jButVypisNeutridene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVypisNeutrideneActionPerformed(evt);
            }
        });

        jButVypis.setText("Vypis");
        jButVypis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVypisActionPerformed(evt);
            }
        });

        jButVlozAkce.setText("VlozAkce");
        jButVlozAkce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVlozAkceActionPerformed(evt);
            }
        });

        jButOdeberAkce.setText("DejAkce");
        jButOdeberAkce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOdeberAkceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFNazevMesta))
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtFNazevAkce))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFDen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFMesic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButZpristupni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButOdeber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButReorganizuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButVloz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButGeneruj, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                    .addComponent(jButVypisUtridene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButVypisNeutridene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButVypis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButVlozAkce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButOdeberAkce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtFNazevMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtFNazevAkce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtFDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtFMesic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButZpristupni)
                    .addComponent(jButVloz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButOdeber)
                    .addComponent(jButGeneruj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButReorganizuj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButVypisUtridene)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButVypisNeutridene)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButVypis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButVlozAkce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButOdeberAkce))
        );

        jTxtAUtridena.setColumns(20);
        jTxtAUtridena.setRows(5);
        jScrollPane3.setViewportView(jTxtAUtridena);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButUlozActionPerformed
        String nazev = jTxFUloz.getText();
        if (nazev.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Nezadali jste nazev ukladaneho souboru", "Chyba", WIDTH);
        } else {
            try {
                kalendarUdalosti.uloz(nazev);
                JOptionPane.showMessageDialog(this, "Ulozeno !", "Ulozeno", WIDTH);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jButUlozActionPerformed

    private void KonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_KonecActionPerformed

    private void jButNactiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNactiActionPerformed
        String nazev = jTxFNacti.getText();
        if (nazev.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Nezadali jste nazev nacteneho souboru", "Chyba", WIDTH);
        } else {
            try {
                kalendarUdalosti.nacti(nazev);
                JOptionPane.showMessageDialog(this, "Nacteno !", "Nacteno", WIDTH);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jButNactiActionPerformed

    private void jButZrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButZrusActionPerformed
        try {
            kalendarUdalosti.zrus();
            jTxtACelkova.setText("");
            jTxtAUtridena.setText("");
            jTxtANeutridena.setText("");
            udalosti = null;
            udalostZpristupnena = null;
            JOptionPane.showMessageDialog(this, "Kalendar zrusen", "Zruseno", WIDTH);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButZrusActionPerformed

    private void jButZalozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButZalozActionPerformed
        try {
            kalendarUdalosti = new KalendarUdalosti();
            JOptionPane.showMessageDialog(this, "Kalendar zalozen", "Zalozeno", WIDTH);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButZalozActionPerformed

    private void jTxtFNazevMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFNazevMestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFNazevMestaActionPerformed

    private void jButVypisUtrideneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVypisUtrideneActionPerformed
        int mohutnost = kalendarUdalosti.dejMohutnost();
        try {
            jTxtAUtridena.setText("");
            for (Iterator it = kalendarUdalosti.dejIteratorPriority(); it.hasNext();) {
                jTxtAUtridena.append(it.next().toString() + "\n");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Fronta je prazdna", "Chyba", WIDTH);
        }


    }//GEN-LAST:event_jButVypisUtrideneActionPerformed

    private void jButGenerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGenerujActionPerformed
        try {
            kalendarUdalosti.generujUdalosti();
            JOptionPane.showMessageDialog(this, "Vygenerovano !", "Vygenerovano", WIDTH);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButGenerujActionPerformed

    private void jButVypisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVypisActionPerformed
        try {
            jTxtACelkova.setText("");
            for (Iterator it = kalendarUdalosti.dejIterator(); it.hasNext();) {
                jTxtACelkova.append(it.next().toString() + "\n");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fronta je prazdna", "Chyba", WIDTH);
        }
    }//GEN-LAST:event_jButVypisActionPerformed

    private void jButReorganizujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButReorganizujActionPerformed
        if (udalostZpristupnena != null) {
            jTxtFNazevAkce.setText(udalostZpristupnena.getNazevUdalosti());
            jTxtFNazevMesta.setText(udalostZpristupnena.getMistoKonani());
            int mesic = Integer.parseInt(jTxtFMesic.getText());
            int den = Integer.parseInt(jTxtFDen.getText());
            int rok = 2012;
            Calendar datum = new GregorianCalendar(rok, mesic, den);
            kalendarUdalosti.preplanujAkci(datum);
        } else {
            JOptionPane.showMessageDialog(this, "Neni zpristupnena udalost k reorganizaci", "Chyba", WIDTH);
        }
    }//GEN-LAST:event_jButReorganizujActionPerformed

    private void jButVypisNeutrideneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVypisNeutrideneActionPerformed
        try {
            jTxtANeutridena.setText("");
            for (Iterator it = kalendarUdalosti.dejIteratorNeutridene(); it.hasNext();) {
                jTxtANeutridena.append(it.next().toString() + "\n");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fronta je prazdna", "Chyba", WIDTH);
        }
    }//GEN-LAST:event_jButVypisNeutrideneActionPerformed

    private void jButZpristupniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButZpristupniActionPerformed

        try {
            IUdalost pomocna = kalendarUdalosti.zpristupni();
            udalostZpristupnena = pomocna;
            jTxtFNazevAkce.setText(pomocna.getNazevUdalosti());
            jTxtFNazevMesta.setText(pomocna.getMistoKonani());
            jTxtAUtridena.setText("");
            jTxtAUtridena.append(pomocna.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Prazdny seznam", "Chyba", WIDTH);
        }
    }//GEN-LAST:event_jButZpristupniActionPerformed

    private void jButNastavVelikostPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNastavVelikostPriorityActionPerformed
        try {
            int velikost = Integer.parseInt(jTxtFNastavVelikostPriority.getText());
            System.out.println(velikost);
            kalendarUdalosti.nastavMohutnost(velikost);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Spatne zadane cislo", "Chyba", WIDTH);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Neni zalozen kalendar zalozte kalendar", "Chyba", WIDTH);
        }

    }//GEN-LAST:event_jButNastavVelikostPriorityActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String velikost = Integer.toString(kalendarUdalosti.dejMohutnost());
            jLblVelikostPriority.setText(velikost);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Neni zalozen kalendar zalozte kalendar", "Chyba", WIDTH);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButOdeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOdeberActionPerformed
        try {
            IUdalost pomocna = kalendarUdalosti.odeber();
            jTxtAUtridena.setText("");
            jTxtAUtridena.append(pomocna.toString() + " : Odebrano");

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Seznam je prazdny", "Chyba", WIDTH);
        }

    }//GEN-LAST:event_jButOdeberActionPerformed

    private void jButVlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVlozActionPerformed
        try {
            int mesic = Integer.parseInt(jTxtFMesic.getText());
            int den = Integer.parseInt(jTxtFDen.getText());
            int rok = 2012;
            String nazevAkce = jTxtFNazevAkce.getText();
            String nazevMesta = jTxtFNazevMesta.getText();

            Calendar datum = new GregorianCalendar(rok, mesic, den);
            IUdalost udalost = new Udalost(datum, nazevAkce, nazevMesta);
            kalendarUdalosti.vlozAkci(udalost);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Spatne zadany mesic nebo den", "Chyba", WIDTH);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Neni zalozen kalendar zalozte kalendar", "Chyba", WIDTH);
        }


    }//GEN-LAST:event_jButVlozActionPerformed

    private void jButVlozAkceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVlozAkceActionPerformed
        try {
            kalendarUdalosti.vlozAkce(udalosti);
            JOptionPane.showMessageDialog(this, "Vlozeno", "OK", WIDTH);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Nejsou nahrany zadne Udalosti", "Chyba", WIDTH);
        }

    }//GEN-LAST:event_jButVlozAkceActionPerformed

    private void jButOdeberAkceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOdeberAkceActionPerformed
        try {

            int pocetUdalosti = kalendarUdalosti.dejMohutnost();
            udalosti = new Udalost[pocetUdalosti];
            udalosti = kalendarUdalosti.dejAkce();
            jTxtAUtridena.setText("");
            jTxtAUtridena.append("===Odebrane Akce===\n");
            for (int i = 0; i < udalosti.length; i++) {
                jTxtAUtridena.append(udalosti[i].toString());
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Ve fronte nejsou zadne udalosti", "Chyba", WIDTH);
        }


    }//GEN-LAST:event_jButOdeberAkceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgKulturniAkce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgKulturniAkce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgKulturniAkce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgKulturniAkce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ProgKulturniAkce().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Konec;
    private javax.swing.JButton jButGeneruj;
    private javax.swing.JButton jButNacti;
    private javax.swing.JButton jButNastavVelikostPriority;
    private javax.swing.JButton jButOdeber;
    private javax.swing.JButton jButOdeberAkce;
    private javax.swing.JButton jButReorganizuj;
    private javax.swing.JButton jButUloz;
    private javax.swing.JButton jButVloz;
    private javax.swing.JButton jButVlozAkce;
    private javax.swing.JButton jButVypis;
    private javax.swing.JButton jButVypisNeutridene;
    private javax.swing.JButton jButVypisUtridene;
    private javax.swing.JButton jButZaloz;
    private javax.swing.JButton jButZpristupni;
    private javax.swing.JButton jButZrus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblVelikostPriority;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTxFNacti;
    private javax.swing.JTextField jTxFUloz;
    private javax.swing.JTextArea jTxtACelkova;
    private javax.swing.JTextArea jTxtANeutridena;
    private javax.swing.JTextArea jTxtAUtridena;
    private javax.swing.JTextField jTxtFDen;
    private javax.swing.JTextField jTxtFMesic;
    private javax.swing.JTextField jTxtFNastavVelikostPriority;
    private javax.swing.JTextField jTxtFNazevAkce;
    private javax.swing.JTextField jTxtFNazevMesta;
    // End of variables declaration//GEN-END:variables
}
