/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vizualniCast;

import AbstrFIFO.AbstrFIFO;
import AbstrFIFO.IAbstrFIFO;
import VyrobniProces.IProces;
import VyrobniProces.IProcesManu;
import VyrobniProces.IProcesRobo;
import VyrobniProces.ProcesManu;
import VyrobniProces.ProcesRobo;
import VyrobniProces.VyrobniProces;
import VyrobniProces.enumPozice;
import VyrobniProces.enumReorg;
import java.awt.Color;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Jirka
 */
public class ProgVyrobniProces extends javax.swing.JFrame {

    private VyrobniProces vp = new VyrobniProces();
    private enumPozice poziceVkladanehoPrvku = enumPozice.PRVNI;
    private enumPozice poziceOdebiranehoPrvku = enumPozice.PRVNI;
    private enumPozice poziceZpristupnenehoPrvku = enumPozice.PRVNI;
    private enumReorg poziceReorganizace = enumReorg.AGREGACE;
    private IAbstrFIFO<IProces> fronta = new AbstrFIFO<>();
    private IProces procesManu = new ProcesManu();
    private IProces procesRobo = new ProcesRobo();

    /**
     * Creates new form ProgVyrobniProces
     */
    public ProgVyrobniProces() {
        initComponents();
        jComboBoxVlozProces.addItem(enumPozice.PRVNI);
        jComboBoxVlozProces.addItem(enumPozice.POSLEDNI);
        jComboBoxVlozProces.addItem(enumPozice.PREDCHUDCE);
        jComboBoxVlozProces.addItem(enumPozice.NASLEDNIK);

        jComboBoxOdeberProces.addItem(enumPozice.PRVNI);
        jComboBoxOdeberProces.addItem(enumPozice.POSLEDNI);
        jComboBoxOdeberProces.addItem(enumPozice.PREDCHUDCE);
        jComboBoxOdeberProces.addItem(enumPozice.NASLEDNIK);
        jComboBoxOdeberProces.addItem(enumPozice.AKTUALNI);

        jComboBoxZpristupniProces.addItem(enumPozice.PRVNI);
        jComboBoxZpristupniProces.addItem(enumPozice.POSLEDNI);
        jComboBoxZpristupniProces.addItem(enumPozice.PREDCHUDCE);
        jComboBoxZpristupniProces.addItem(enumPozice.NASLEDNIK);
        jComboBoxZpristupniProces.addItem(enumPozice.AKTUALNI);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonGroupProcesy = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaText = new javax.swing.JTextArea();
        jButtonVypisProcesy = new javax.swing.JButton();
        jButtonZrus = new javax.swing.JButton();
        jButtonKonec = new javax.swing.JButton();
        jButtonNacti = new javax.swing.JButton();
        jButtonVlozProces = new javax.swing.JButton();
        jComboBoxVlozProces = new javax.swing.JComboBox();
        jComboBoxOdeberProces = new javax.swing.JComboBox();
        jComboBoxZpristupniProces = new javax.swing.JComboBox();
        jButtonOdeberProces = new javax.swing.JButton();
        jButtonZpristupniProces = new javax.swing.JButton();
        jRadioButtonProcesManualni = new javax.swing.JRadioButton();
        jRadioButtonProcesRoboticky = new javax.swing.JRadioButton();
        jTextFieldID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelCasTrvani = new javax.swing.JLabel();
        jLabelPocetLidi = new javax.swing.JLabel();
        jTextFieldCas = new javax.swing.JTextField();
        jTextFieldPocetLidi = new javax.swing.JTextField();
        jButtonVlozProcesRucni = new javax.swing.JButton();
        jTextFieldZpristupni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonUloz = new javax.swing.JButton();
        jButtonGeneruj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPocetPrvku = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFronta = new javax.swing.JTextArea();
        jButtonZobrazFrontu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCasReorganizace = new javax.swing.JTextField();
        jButtonVytipujKandidaty = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTypReorganizace = new javax.swing.JComboBox();
        jButtonReorganizuj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jTextAreaText.setColumns(20);
        jTextAreaText.setRows(5);
        jScrollPane1.setViewportView(jTextAreaText);

        jButtonVypisProcesy.setText("VypisProcesy");
        jButtonVypisProcesy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVypisProcesyActionPerformed(evt);
            }
        });

        jButtonZrus.setText("Zrus");
        jButtonZrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZrusActionPerformed(evt);
            }
        });

        jButtonKonec.setText("Konec");
        jButtonKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonecActionPerformed(evt);
            }
        });

        jButtonNacti.setText("Nacti");
        jButtonNacti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNactiActionPerformed(evt);
            }
        });

        jButtonVlozProces.setText("VlozProces");
        jButtonVlozProces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVlozProcesActionPerformed(evt);
            }
        });

        jComboBoxVlozProces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVlozProcesActionPerformed(evt);
            }
        });

        jComboBoxOdeberProces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOdeberProcesActionPerformed(evt);
            }
        });

        jComboBoxZpristupniProces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxZpristupniProcesActionPerformed(evt);
            }
        });

        jButtonOdeberProces.setText("OdeberProces");
        jButtonOdeberProces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdeberProcesActionPerformed(evt);
            }
        });

        jButtonZpristupniProces.setText("ZpristupniProces");
        jButtonZpristupniProces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZpristupniProcesActionPerformed(evt);
            }
        });

        jbuttonGroupProcesy.add(jRadioButtonProcesManualni);
        jRadioButtonProcesManualni.setSelected(true);
        jRadioButtonProcesManualni.setText("ProcesManualni");
        jRadioButtonProcesManualni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProcesManualniActionPerformed(evt);
            }
        });

        jbuttonGroupProcesy.add(jRadioButtonProcesRoboticky);
        jRadioButtonProcesRoboticky.setText("ProcesRoboticky");
        jRadioButtonProcesRoboticky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProcesRobotickyActionPerformed(evt);
            }
        });

        jLabelID.setText("id robo/man");

        jLabelCasTrvani.setText("cas. trvani");

        jLabelPocetLidi.setText("pocet Lidi");

        jTextFieldPocetLidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPocetLidiActionPerformed(evt);
            }
        });

        jButtonVlozProcesRucni.setText("VlozProces");
        jButtonVlozProcesRucni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVlozProcesRucniActionPerformed(evt);
            }
        });

        jTextFieldZpristupni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZpristupniActionPerformed(evt);
            }
        });

        jLabel1.setText("Zpristupneno: ");

        jButtonUloz.setText("Uloz");
        jButtonUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlozActionPerformed(evt);
            }
        });

        jButtonGeneruj.setText("Generuj");
        jButtonGeneruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerujActionPerformed(evt);
            }
        });

        jLabel2.setText("Pocet Prvku:");

        jTextFieldPocetPrvku.setText("0");

        jTextAreaFronta.setColumns(20);
        jTextAreaFronta.setRows(5);
        jScrollPane2.setViewportView(jTextAreaFronta);

        jButtonZobrazFrontu.setText("ZobrazFrontu");
        jButtonZobrazFrontu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZobrazFrontuActionPerformed(evt);
            }
        });

        jLabel3.setText("Reorganizace");

        jLabel4.setText("cas:");

        jTextFieldCasReorganizace.setText("0");

        jButtonVytipujKandidaty.setText("Vytipuj");
        jButtonVytipujKandidaty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVytipujKandidatyActionPerformed(evt);
            }
        });

        jLabel5.setText("Typ:");

        jComboBoxTypReorganizace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AGREGACE", "DEKOMPOZICE", " " }));

        jButtonReorganizuj.setText("Reorganizuj");
        jButtonReorganizuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReorganizujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jTextFieldZpristupni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonZobrazFrontu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonVytipujKandidaty, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReorganizuj, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxTypReorganizace, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCasReorganizace)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxZpristupniProces, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonZpristupniProces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOdeberProces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxOdeberProces, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVypisProcesy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVlozProces)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxVlozProces, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCasTrvani)
                                        .addComponent(jLabelPocetLidi))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldPocetLidi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButtonVlozProcesRucni))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonProcesManualni)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButtonProcesRoboticky))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel2)
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonGeneruj, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPocetPrvku, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jButtonKonec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUloz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNacti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonZrus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelID)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCasTrvani))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPocetLidi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPocetLidi)
                            .addComponent(jButtonVlozProcesRucni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonProcesManualni)
                            .addComponent(jRadioButtonProcesRoboticky))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVlozProces)
                            .addComponent(jComboBoxVlozProces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldPocetPrvku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGeneruj)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNacti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUloz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButtonZrus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonKonec))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonZpristupniProces)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxZpristupniProces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOdeberProces)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxOdeberProces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVypisProcesy)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxTypReorganizace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldCasReorganizace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVytipujKandidaty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonZobrazFrontu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReorganizuj))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldZpristupni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxVlozProcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVlozProcesActionPerformed
        poziceVkladanehoPrvku = (enumPozice) (jComboBoxVlozProces.getSelectedItem());
    }//GEN-LAST:event_jComboBoxVlozProcesActionPerformed

    private void jButtonVlozProcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVlozProcesActionPerformed
        Iterator it = null;
        it = vp.dejIterator();
        jTextAreaText.setText(null);
        if (jRadioButtonProcesManualni.isSelected()) {
            procesManu = new ProcesManu();
            vp.vlozProces(procesManu, poziceVkladanehoPrvku);

        }
        if (jRadioButtonProcesRoboticky.isSelected()) {
            procesRobo = new ProcesRobo();
            vp.vlozProces(procesRobo, poziceVkladanehoPrvku);
        }
        while (it.hasNext()) {
            IProces pom = (IProces) it.next();
            jTextAreaText.append(pom.toString() + "\n");
        }
    }//GEN-LAST:event_jButtonVlozProcesActionPerformed

    private void jButtonKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonKonecActionPerformed

    private void jButtonZrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZrusActionPerformed
        vp.zrus();
        fronta.zrus();
        jTextAreaFronta.setText(" ");
        jTextAreaText.setText(" ");
    }//GEN-LAST:event_jButtonZrusActionPerformed

    private void jComboBoxOdeberProcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOdeberProcesActionPerformed
        poziceOdebiranehoPrvku = (enumPozice) (jComboBoxOdeberProces.getSelectedItem());
    }//GEN-LAST:event_jComboBoxOdeberProcesActionPerformed

    private void jButtonVypisProcesyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVypisProcesyActionPerformed
        Iterator it = null;
        it = vp.dejIterator();
        jTextAreaText.setText("");
        try {
            while (it.hasNext()) {
                IProces pom = (IProces) it.next();
                jTextAreaText.append(pom.toString() + "\n");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vyrobni proces je prazdny : " + e.getMessage());
        }


    }//GEN-LAST:event_jButtonVypisProcesyActionPerformed

    private void jButtonOdeberProcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdeberProcesActionPerformed
        try {
            vp.odeberProces(poziceOdebiranehoPrvku);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vyrobni proces je prazdny : " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonOdeberProcesActionPerformed

    private void jButtonVlozProcesRucniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVlozProcesRucniActionPerformed
        try {
            if (jRadioButtonProcesManualni.isSelected()) {
                procesManu = new ProcesManu(jTextFieldID.getText(), Integer.parseInt(jTextFieldPocetLidi.getText()),
                        Integer.parseInt(jTextFieldCas.getText()));
                vp.vlozProces(procesManu, poziceVkladanehoPrvku);
            }
            if (jRadioButtonProcesRoboticky.isSelected()) {

                procesRobo = new ProcesRobo(jTextFieldID.getText(), Integer.parseInt(jTextFieldCas.getText()));
                vp.vlozProces(procesRobo, poziceVkladanehoPrvku);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Spatne zadane udaje");
        }

    }//GEN-LAST:event_jButtonVlozProcesRucniActionPerformed

    private void jButtonZpristupniProcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZpristupniProcesActionPerformed
        try {
            IProces proces = null;
            proces = vp.zpristupniProces(poziceZpristupnenehoPrvku);
            jTextFieldZpristupni.setText(proces.toString());
            repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vyrobni proces je prazdny : " + e.getMessage());
        }

    }//GEN-LAST:event_jButtonZpristupniProcesActionPerformed

    private void jTextFieldZpristupniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZpristupniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZpristupniActionPerformed

    private void jComboBoxZpristupniProcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxZpristupniProcesActionPerformed
        poziceZpristupnenehoPrvku = (enumPozice) jComboBoxZpristupniProces.getSelectedItem();
    }//GEN-LAST:event_jComboBoxZpristupniProcesActionPerformed

    private void jButtonNactiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNactiActionPerformed
        try {
            vp.nacti();
            jTextAreaText.append("Uspesne nacteno \n");
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jButtonNactiActionPerformed

    private void jButtonUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlozActionPerformed
        try {
            vp.uloz();
            jTextAreaText.append("Uspesne ulozeno \n");
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jButtonUlozActionPerformed

    private void jButtonGenerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerujActionPerformed
        int pocetPrvku = 0;
        int genProc = 0;
        int genCas = 0;
        int genPocetPracovniknu = 0;
        IProcesManu manual = null;
        IProcesRobo robot = null;
        try {
            pocetPrvku = Integer.parseInt(jTextFieldPocetPrvku.getText());
            for (int i = 0; i < pocetPrvku; i++) {
                genProc = (int) ((Math.random() * 2) + 1);
                genCas = (int) ((Math.random() * 20) + 1);
                genPocetPracovniknu = (int) ((Math.random() * 10) + 1);
                if (genProc == 1) {
                    manual = new ProcesManu();
                    vp.vlozProces(manual, enumPozice.PRVNI);
                } else {
                    robot = new ProcesRobo();
                    vp.vlozProces(robot, enumPozice.PRVNI);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Spatne zadane cislo \n" + e.getMessage());
        }
    }//GEN-LAST:event_jButtonGenerujActionPerformed

    private void jButtonVytipujKandidatyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVytipujKandidatyActionPerformed

        int casReorganizace = 0;
        int cislo = 0;
        cislo = jComboBoxTypReorganizace.getSelectedIndex();
        try {


            if (cislo == 0) {
                poziceReorganizace = enumReorg.AGREGACE;
            } else {
                poziceReorganizace = enumReorg.DEKOMPOZICE;
            }
            System.out.println(cislo);
            casReorganizace = Integer.parseInt(jTextFieldCasReorganizace.getText());
            fronta = vp.vytipujKandidatiReorg(casReorganizace, poziceReorganizace);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fronta je prazda prvky nesplnuji kriterium");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonVytipujKandidatyActionPerformed

    private void jButtonZobrazFrontuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZobrazFrontuActionPerformed
        Iterator it = null;
        it = fronta.dejIterator();
        IProces pr = null;
        int i = 1;
        try {
            jTextAreaFronta.setText(null);
            while (it.hasNext()) {
                pr = (IProces) it.next();
                jTextAreaFronta.append(i+" : "+pr.toString() + "\n");
                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fronta je prazdna");
        }

    }//GEN-LAST:event_jButtonZobrazFrontuActionPerformed

    private void jButtonReorganizujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReorganizujActionPerformed

        vp.reorganizace(poziceReorganizace, fronta);
    }//GEN-LAST:event_jButtonReorganizujActionPerformed

    private void jTextFieldPocetLidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPocetLidiActionPerformed
    }//GEN-LAST:event_jTextFieldPocetLidiActionPerformed

    private void jRadioButtonProcesRobotickyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProcesRobotickyActionPerformed
        if(jRadioButtonProcesRoboticky.isSelected()){
        jTextFieldPocetLidi.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonProcesRobotickyActionPerformed

    private void jRadioButtonProcesManualniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProcesManualniActionPerformed
         if(jRadioButtonProcesManualni.isSelected()){
        jTextFieldPocetLidi.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonProcesManualniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgVyrobniProces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgVyrobniProces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgVyrobniProces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgVyrobniProces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ProgVyrobniProces().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGeneruj;
    private javax.swing.JButton jButtonKonec;
    private javax.swing.JButton jButtonNacti;
    private javax.swing.JButton jButtonOdeberProces;
    private javax.swing.JButton jButtonReorganizuj;
    private javax.swing.JButton jButtonUloz;
    private javax.swing.JButton jButtonVlozProces;
    private javax.swing.JButton jButtonVlozProcesRucni;
    private javax.swing.JButton jButtonVypisProcesy;
    private javax.swing.JButton jButtonVytipujKandidaty;
    private javax.swing.JButton jButtonZobrazFrontu;
    private javax.swing.JButton jButtonZpristupniProces;
    private javax.swing.JButton jButtonZrus;
    private javax.swing.JComboBox jComboBoxOdeberProces;
    private javax.swing.JComboBox jComboBoxTypReorganizace;
    private javax.swing.JComboBox jComboBoxVlozProces;
    private javax.swing.JComboBox jComboBoxZpristupniProces;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCasTrvani;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPocetLidi;
    private javax.swing.JRadioButton jRadioButtonProcesManualni;
    private javax.swing.JRadioButton jRadioButtonProcesRoboticky;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaFronta;
    private javax.swing.JTextArea jTextAreaText;
    private javax.swing.JTextField jTextFieldCas;
    private javax.swing.JTextField jTextFieldCasReorganizace;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPocetLidi;
    private javax.swing.JTextField jTextFieldPocetPrvku;
    private javax.swing.JTextField jTextFieldZpristupni;
    private javax.swing.ButtonGroup jbuttonGroupProcesy;
    // End of variables declaration//GEN-END:variables
}
